import { Router } from 'express';
import { getPublicConsultations, getAllConsultations, createConsultation, updateConsultation, deleteConsultation, toggleConsultation } from '../Controllers/consultationController.mjs';
import { protect } from '../Middlewares/auth.mjs';
const router = Router();
router.get('/public', getPublicConsultations);
router.get('/', protect, getAllConsultations);
router.post('/', protect, createConsultation);
router.put('/:id', protect, updateConsultation);
router.delete('/:id', protect, deleteConsultation);
router.patch('/:id/toggle', protect, toggleConsultation);
export default router;
