import { Router } from 'express';
import { getPublicTraining, getAllTraining, createTraining, updateTraining, deleteTraining, verifyAndCreateBooking, getAllBookings } from '../Controllers/trainingController.mjs';
import { protect } from '../Middlewares/auth.mjs';
const router = Router();
router.get('/public', getPublicTraining);
router.get('/', protect, getAllTraining);
router.post('/', protect, createTraining);
router.put('/:id', protect, updateTraining);
router.delete('/:id', protect, deleteTraining);
router.post('/book/verify', verifyAndCreateBooking);
router.get('/bookings', protect, getAllBookings);
export default router;
